### ISSUE TITLE
Windows?

### ISSUE THREAD

**Issue by Helveg** [BlueBrain/nmodl#1112]
Hi! I noticed I can't install `nmodl` on Windows?

**Comment by Helveg** [comment]
@alkino Any chance we could try to build Python wheels with `scikit-build-core` and `cibuildwheel`? They usually maassively reduce the burden of maintenance to produce cross-platform wheels for all the architectures and python versions

**Comment by pramodk** [comment]
@Helveg: I would say it's not unreasonable to expect NMODL easily available on Windows. Just we need to see when we could have a bit of time to experiment about this.

**Comment by JCGoran** [comment]
As an update, I am quite certain Windows should be doable at some point, but it currently fails with a very basic-looking error:

```plaintext
2024-02-16T14:06:23.1217607Z   Project "C:\Users\runneradmin\AppData\Local\Temp\tmplpg9idi8\build\src\pybind\_nmodl.vcxproj" (3) is building "C:\Users\runneradmin\AppData\Local\Temp\tmplpg9idi8\build\src\language\pyastgen.vcxproj" (7) on node 1 (default targets).
2024-02-16T14:06:23.1218753Z   PrepareForBuild:
2024-02-16T14:06:23.1219050Z     Creating directory "x64\Release\pyastgen\".
2024-02-16T14:06:23.1219497Z     Creating directory "x64\Release\pyastgen\pyastgen.tlog\".
2024-02-16T14:06:23.1219903Z   InitializeBuildStatus:
2024-02-16T14:06:23.1220482Z     Creating "x64\Release\pyastgen\pyastgen.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
2024-02-16T14:06:23.1221212Z     Touching "x64\Release\pyastgen\pyastgen.tlog\unsuccessfulbuild".
2024-02-16T14:06:23.1221659Z   ComputeCustomBuildOutput:
2024-02-16T14:06:23.1222172Z     Creating directory "C:\Users\runneradmin\AppData\Local\Temp\tmplpg9idi8\build\src\ast\".
2024-02-16T14:06:23.1222695Z   CustomBuild:
2024-02-16T14:06:23.1224776Z     "The build of 'C:\Users\runneradmin\AppData\Local\Temp\tmplpg9idi8\build\CMakeFiles\b82c1270eaa8e7d1404e43aad4f2511c\pyastgen.rule' depends on 'C:\USERS\RUNNERADMIN\APPDATA\LOCAL\TEMP\TMPLPG9IDI8\BUILD\SRC\AST\AST.CPP' which is produced by the build of 'C:\Users\runneradmin\AppData\Local\Temp\tmplpg9idi8\build\CMakeFiles\0700211361b712a5e3a2ce3a8a2244d4\after_block.hpp.rule'. The items cannot be built in parallel."
2024-02-16T14:06:23.1227533Z     -- NMODL : GENERATING AST CLASSES WITH PYTHON GENERATOR! --
2024-02-16T14:06:23.1227966Z     Traceback (most recent call last):
2024-02-16T14:06:23.1234647Z       File "D:\a\nmodl\nmodl\src\language\code_generator.py", line 408, in <module>
2024-02-16T14:06:23.1235216Z         main()
2024-02-16T14:06:23.1235678Z       File "D:\a\nmodl\nmodl\src\language\code_generator.py", line 391, in main
2024-02-16T14:06:23.1236189Z         if task.execute():
2024-02-16T14:06:23.1236468Z            ^^^^^^^^^^^^^^
2024-02-16T14:06:23.1236936Z       File "D:\a\nmodl\nmodl\src\language\code_generator.py", line 246, in execute
2024-02-16T14:06:23.1237441Z         return self.render()
2024-02-16T14:06:23.1237718Z                ^^^^^^^^^^^^^
2024-02-16T14:06:23.1238165Z       File "D:\a\nmodl\nmodl\src\language\code_generator.py", line 315, in render
2024-02-16T14:06:23.1238817Z         content = self.app.jinja_template(self.input).render(**self.context)
2024-02-16T14:06:23.1239288Z                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-16T14:06:23.1239850Z       File "D:\a\nmodl\nmodl\src\language\code_generator.py", line 111, in jinja_template
2024-02-16T14:06:23.1240419Z         return self.jinja_env.get_template(name)
2024-02-16T14:06:23.1240787Z                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-16T14:06:23.1241781Z       File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-xi5otx13\overlay\Lib\site-packages\jinja2\environment.py", line 1010, in get_template
2024-02-16T14:06:23.1242667Z         return self._load_template(name, globals)
2024-02-16T14:06:23.1243044Z                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-16T14:06:23.1244003Z       File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-xi5otx13\overlay\Lib\site-packages\jinja2\environment.py", line 969, in _load_template
2024-02-16T14:06:23.1244972Z         template = self.loader.load(self, name, self.make_globals(globals))
2024-02-16T14:06:23.1245469Z                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-16T14:06:23.1246378Z       File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-xi5otx13\overlay\Lib\site-packages\jinja2\loaders.py", line 125, in load
2024-02-16T14:06:23.1247395Z         source, filename, uptodate = self.get_source(environment, name)
2024-02-16T14:06:23.1247879Z                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-16T14:06:23.1248835Z       File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-xi5otx13\overlay\Lib\site-packages\jinja2\loaders.py", line 194, in get_source
2024-02-16T14:06:23.1249671Z         pieces = split_template_path(template)
2024-02-16T14:06:23.1250026Z                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-16T14:06:23.1250956Z       File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-xi5otx13\overlay\Lib\site-packages\jinja2\loaders.py", line 35, in split_template_path
2024-02-16T14:06:23.1251811Z         raise TemplateNotFound(template)
2024-02-16T14:06:23.1252213Z     jinja2.exceptions.TemplateNotFound: ast\all.hpp
2024-02-16T14:06:23.1255126Z   C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(254,5): error MSB8066: Custom build for 'C:\Users\runneradmin\AppData\Local\Temp\tmplpg9idi8\build\CMakeFiles\0700211361b712a5e3a2ce3a8a2244d4\after_block.hpp.rule;C:\Users\runneradmin\AppData\Local\Temp\tmplpg9idi8\build\CMakeFiles\b82c1270eaa8e7d1404e43aad4f2511c\pyastgen.rule;D:\a\nmodl\nmodl\src\language\CMakeLists.txt' exited with code 1. [C:\Users\runneradmin\AppData\Local\Temp\tmplpg9idi8\build\src\language\pyastgen.vcxproj]
```
For the full build log, see for instance [here](https://github.com/BlueBrain/nmodl/actions/runs/7931668887/job/21656418918).
I'm not really sure whether the problem is in Jinja, or NMODL (I don't see how because we strictly use `pathlib` there, unless there is a bug in `pathlib` itself), or something to do with the environment MSVC sets up, because the file _is_ there, and this only happens on Windows. Unfortunately, I don't have a local Windows machine to do further investigation of the problem.
