### ISSUE TITLE
make clang-format fails on BB5 CI with fails with PermissionError: [Errno 1] Operation not permitted

### ISSUE THREAD

**Issue by pramodk** [BlueBrain/nmodl#267]
While running format tests on BB5 I see:

```
$ make clang-format
[  0%] -- NMODL : GENERATING AST CLASSES WITH PYTHON GENERATOR! --
Traceback (most recent call last):
  File "/gpfs/bbp.cscs.ch/project/proj16/kumbhar/pramod_scratch/tmp/nmodl/src/language/code_generator.py", line 56, in <module>
    shutil.copy2(clang_format_file, temp_dir)
  File "/gpfs/bbp.cscs.ch/project/proj16/kumbhar/pramod_scratch/tmp/nmodl/build/venv/lib/python3.7/shutil.py", line 267, in copy2
    copystat(src, dst, follow_symlinks=follow_symlinks)
  File "/gpfs/bbp.cscs.ch/project/proj16/kumbhar/pramod_scratch/tmp/nmodl/build/venv/lib/python3.7/shutil.py", line 206, in copystat
    follow_symlinks=follow)
PermissionError: [Errno 1] Operation not permitted
```

This is because we try to copy .clang-format file to /tmp and if there exist one from different user then we can't overwrite:

```
$ ll /tmp/.clang-format
-rw-rw---- 1 magkanar bbp 2702 Mar  7 10:57 /tmp/.clang-format
```

**Comment by pramodk** [comment]
fixed in #265
