### ISSUE TITLE
Crash when analysing mod with global assignment.

### ISSUE THREAD

**Issue by halfflat** [BlueBrain/nmodl#330]
Running `nmodl` on a mod file which writes a value in `BREAKPOINT` to an `ASSIGNED` variable which is `GLOBAL` causes a crash when emitting some diagnostic output. An example of such a mod file is the NEURON `hh` mechanism.

Built with clang 10.0.0 in an Arch Linux environment, configured with `-DCMAKE_BUILD_TYPE=debug`:
```
% cat test.mod
NEURON {
    SUFFIX test
    GLOBAL x
}
ASSIGNED {
    x
}
BREAKPOINT {
    x = 1
}
% ./bin/nmodl test.mod
[NMODL] [info] :: Processing test.mod
[NMODL] [info] :: Running symtab visitor
[NMODL] [info] :: Running code compatibility checker
*** stack smashing detected ***: terminated
zsh: abort (core dumped)  ./bin/nmodl test.mod
```

Stack trace from core dump:
```
0x00007f5cbe697ce5 in raise () from /usr/lib/libc.so.6
#1  0x00007f5cbe681857 in abort () from /usr/lib/libc.so.6
#2  0x00007f5cbe6db2b0 in __libc_message () from /usr/lib/libc.so.6
#3  0x00007f5cbe76b06a in __fortify_fail () from /usr/lib/libc.so.6
#4  0x00007f5cbe76b034 in __stack_chk_fail () from /usr/lib/libc.so.6
#5  0x000055b802248257 in fmt::v6::format<char [119], std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char> (format_str=..., args=..., args=...) at [...]/nmodl/ext/spdlog/include/spdlog/fmt/bundled/core.h:1476
#6  0x000055b802246d98 in fmt::v6::internal::udl_formatter<char, (char)34, (char)123, (char)125, (char)34, (char)32, (char)118, (char)97, (char)114, (char)105, (char)97, (char)98, (char)108, (char)101, (char)32, (char)102, (char)111, (char)117, (char)110, (char)100, (char)32, (char)97, (char)116, (char)32, (char)91, (char)123, (char)125, (char)93, (char)32, (char)115, (char)104, (char)111, (char)117, (char)108, (char)100, (char)32, (char)98, (char)101, (char)32, (char)100, (char)101, (char)102, (char)105, (char)110, (char)101, (char)100, (char)32, (char)97, (char)115, (char)32, (char)97, (char)32, (char)82, (char)65, (char)78, (char)71, (char)69, (char)32, (char)118, (char)97, (char)114, (char)105, (char)97, (char)98, (char)108, (char)101, (char)32, (char)105, (char)110, (char)115, (char)116, (char)101, (char)97, (char)100, (char)32, (char)111, (char)102, (char)32, (char)71, (char)76, (char)79, (char)66, (char)65, (char)76, (char)32, (char)116, (char)111, (char)32, (char)101, (char)110, (char)97, (char)98, (char)108, (char)101, (char)32, (char)98, (char)97, (char)99, (char)107, (char)101, (char)110, (char)100, (char)32, (char)116, (char)114, (char)97, (char)110, (char)115, (char)102, (char)111, (char)114, (char)109, (char)97, (char)116, (char)105, (char)111, (char)110, (char)115, (char)10>::operator()<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > (this=0x7ffdad1dc228, args=..., args=...) at [...]/nmodl/ext/spdlog/include/spdlog/fmt/bundled/format.h:3424
#7  0x000055b80224567d in nmodl::codegen::CodegenCompatibilityVisitor::return_error_global_var[abi:cxx11](nmodl::ast::Ast&, std::shared_ptr<nmodl::ast::Ast> const&) (this=0x7ffdad1dd5d0, node=..., ast_node=warning: RTTI symbol not found for class 'std::_Sp_counted_ptr<nmodl::ast::GlobalVar*, (__gnu_cxx::_Lock_policy)2>'
warning: RTTI symbol not found for class 'std::_Sp_counted_ptr<nmodl::ast::GlobalVar*, (__gnu_cxx::_Lock_policy)2>'

std::shared_ptr<nmodl::ast::Ast> (use count 4, weak count 1) = {...}) at [...]/nmodl/src/codegen/codegen_compatibility_visitor.cpp:50
#8  0x000055b802246155 in nmodl::codegen::CodegenCompatibilityVisitor::find_unhandled_ast_nodes (this=0x7ffdad1dd5d0, node=...) at [...]/nmodl/src/codegen/codegen_compatibility_visitor.cpp:120
#9  0x000055b80211f2c2 in main (argc=2, argv=0x7ffdad1e2048) at [...]/nmodl/src/nmodl/main.cpp:310
```

**Comment by pramodk** [comment]
Thanks Sam for the bug report! I believe #331 should have fixed the issue in latest master.

**Comment by halfflat** [comment]
Thanks, I'll give it a go!

**Comment by halfflat** [comment]
Happy to confirm that it does not crash!

**Comment by pramodk** [comment]
thanks for confirming!
