### ISSUE TITLE
Documentation CI fails

### ISSUE THREAD

**Issue by olupton** [BlueBrain/nmodl#876]
Starting today the documentation and wheel CI builds are failing, e.g. https://dev.azure.com/pramodskumbhar/nmodl/_build/results?buildId=4098&view=logs&j=e663e406-bc69-5454-a50c-2daf70096c50&t=44a6ba8e-413d-536f-de25-37de658d0279:
```
Traceback (most recent call last):
  File "setup.py", line 145, in <module>
    install_requires=install_requirements,
  File "/root/nmodl/nmodl_build_venv36/lib/python3.6/site-packages/skbuild/setuptools_wrap.py", line 750, in setup
    return setuptools.setup(*args, **kw)
  File "/root/nmodl/nmodl_build_venv36/lib/python3.6/site-packages/setuptools/__init__.py", line 152, in setup
    _install_setup_requires(attrs)
  File "/root/nmodl/nmodl_build_venv36/lib/python3.6/site-packages/setuptools/__init__.py", line 147, in _install_setup_requires
    dist.fetch_build_eggs(dist.setup_requires)
  File "/root/nmodl/nmodl_build_venv36/lib/python3.6/site-packages/setuptools/dist.py", line 815, in fetch_build_eggs
    replace_conflicting=True,
  File "/root/nmodl/nmodl_build_venv36/lib/python3.6/site-packages/pkg_resources/__init__.py", line 782, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (Sphinx 5.0.0 (/root/nmodl/.eggs/Sphinx-5.0.0-py3.6.egg), Requirement.parse('sphinx<5,>=3.1'), {'myst-parser'})
```

**Comment by olupton** [comment]
This is probably related to sphinx 5.0.0 being released yesterday: https://pypi.org/project/Sphinx/5.0.0
